feat(starter): support spring config server/appolo/nacos
redisson/redisson pull request #2983
Opened 2020-08-17 11:32 UTC by anjia0532

support spring config server/appolo/nacos
compatible spring boot's
config (`spring.redis.redisson.config=classpath:redisson.yaml`)

Closes #2918
Closes #2765
Closes #2086
Closes #1829
Closes #2520

2020-08-24 02:22 UTC, anjia0532 commented on redisson-spring-boot-starter/README.md
> +    config: classpath:redisson.yaml
it's a  break change to rename `config` to `configFile` ,`configBlock` to `config`.

```
## yaml code
redisson: both of support file or block
redissonFile: classpath:redisson.yaml
redissonBlock: |
#....

## java code
String config;
// hide spring data redis config...
if redisson.contains("classpath"){
config = configFile.content;
}else{
config  = configBlock;
}
```

2020-09-03 01:20 UTC, anjia0532 commented
any process?

2020-09-05 05:05 UTC, mrniko commented on redisson-spring-boot-starter/README.md
> +    config: classpath:redisson.yaml
Can we check if config line is single line then try to load it as file overwise use as yaml config block?

2020-09-05 05:06 UTC, mrniko commented
@anjia0532

I replied in comment

2020-09-05 06:36 UTC, anjia0532 commented on redisson-spring-boot-starter/README.md
> +    config: classpath:redisson.yaml
for spring cloud scene , people use spring config server or alibaba nacos ... to management and apply properties .  load another file is not friendly(you must be write a config file in your classpath(include host,password,db index ...)).

2020-09-05 06:36 UTC, anjia0532 commented
@anjia0532 thanks for your replay.

2020-09-08 05:15 UTC, mrniko requested changes

2020-09-08 05:15 UTC, mrniko commented on redisson-spring-boot-starter/README.md
> +    config: classpath:redisson.yaml
In this case we need to introduce `file` property. So we could write it like this:
```yaml
 redisson: 
    config:
         file: classpath:redisson.yaml
```
or 
```yaml
 redisson: 
    config:
      clusterServersConfig:
        idleConnectionTimeout: 10000
        connectTimeout: 10000
        timeout: 3000
        retryAttempts: 3
        retryInterval: 1500
        failedSlaveReconnectionInterval: 3000
        failedSlaveCheckInterval: 60000
        password: null
        subscriptionsPerConnection: 5
        clientName: null
        loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
        subscriptionConnectionMinimumIdleSize: 1
        subscriptionConnectionPoolSize: 50
        slaveConnectionMinimumIdleSize: 24
        slaveConnectionPoolSize: 64
        masterConnectionMinimumIdleSize: 24
        masterConnectionPoolSize: 64
        readMode: "SLAVE"
        subscriptionMode: "SLAVE"
        nodeAddresses:
        - "redis://127.0.0.1:7004"
        - "redis://127.0.0.1:7001"
        - "redis://127.0.0.1:7000"
        scanInterval: 1000
        pingConnectionInterval: 0
        keepAlive: false
        tcpNoDelay: false
      threads: 16
      nettyThreads: 32
      codec: !<org.redisson.codec.FstCodec> {}
      transportMode: "NIO"
```

2020-09-08 11:49 UTC, anjia0532 commented
@mrniko  in your idea, it's a break change.  I prefer backward compatibility.

2020-09-08 12:20 UTC, mrniko commented on redisson-spring-boot-starter/README.md
> +    config: classpath:redisson.yaml
Yes, it's a breaking change which will be mentioned in release notes with bold. Because block, configBlock sounds ugly, I'm sorry.

2020-09-21 05:16 UTC, wltj920 commented
### **I am looking forward to this feature**

2020-09-22 01:17 UTC, anjia0532 commented
any process?

2020-09-28 04:57 UTC, mrniko commented
@anjia0532 

I gave my last comment here https://github.com/redisson/redisson/pull/2983/files#r484872474

2020-09-28 05:56 UTC, anjia0532 commented
@mrniko 
Sorry, I missed your reply. It has been amended as you instructed.

2020-09-28 07:28 UTC, mrniko approved these changes

2020-09-28 07:28 UTC, merged

2020-09-28 07:28 UTC, mrniko commented
Thanks for contribution