fix: connection leak when initConnections
redisson/redisson pull request #3295
Opened 2020-12-16 09:15 UTC by mikawudi

add initing status in entry, and set entry freezed status null when all connection inited

Signed-off-by: xujie <mikawudi@qq.com>

2020-12-16 09:18 UTC, mikawudi commented
not wait pubSubConnectionPool inited, beacuse i think pubSubConnectionPool minimumIdleSize is alway less than 10

2020-12-18 08:04 UTC, mrniko requested changes

2020-12-18 08:04 UTC, mrniko commented on redisson/src/main/java/org/redisson/connection/balancer/LoadBalancerManager.java
> +                    slaveConnectionPool.initConnections(entry).onComplete((r, ex) -> {
please use AsyncCountDownLatch here. Both handlers slaveConnectionPool, pubSubConnectionPool invoke countDown method and in latch callback we do rest logic.

2020-12-18 08:04 UTC, mrniko commented on redisson/src/main/java/org/redisson/connection/balancer/LoadBalancerManager.java
> +                if (!entry.isIniting()) {
use AtomicBoolean.compareAndSet method

2020-12-18 08:06 UTC, mrniko requested changes

2020-12-18 08:06 UTC, mrniko commented on redisson/src/main/java/org/redisson/connection/ClientConnectionsEntry.java
> +    private volatile boolean initing = false;
rename this setting to `initialized`

2020-12-21 09:24 UTC, mrniko requested changes

2020-12-21 09:24 UTC, mrniko commented on redisson/src/main/java/org/redisson/connection/balancer/LoadBalancerManager.java
> +                    AtomicInteger initedCounter = new AtomicInteger(2);
we can use CountableListener here:
```java
RPromise<Void> promise = new RedissonPromise<Void>();
promise.onComplete((r, ex) -> {
     if (ex == null) {
         entry.setFreezeReason(null);
     }
});
CountableListener listener = new CountableListener(promise, null, 2);
slaveConnectionPool.initConnections(entry).onComplete(() -> {listener.decCounter()});
pubSubConnectionPool.initConnections(entry).onComplete(() -> {listener.decCounter()});
```

2020-12-21 09:59 UTC, mrniko approved these changes

2020-12-21 13:31 UTC, merged

2020-12-21 13:31 UTC, mrniko commented
Thanks for contribution!