feat: add config to check sentinel result slave node is in master-sla…
redisson/redisson pull request #3478
Opened 2021-03-15 08:04 UTC by mikawudi

add config to check sentinel result slave node is in master-slave syncing status

Signed-off-by: xujie <mikawudi@qq.com>

2021-03-15 08:05 UTC, mikawudi commented
more info in this issue: https://github.com/redisson/redisson/issues/3345

2021-03-17 06:34 UTC, mrniko requested changes

2021-03-17 06:34 UTC, mrniko commented on redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
> +import org.springframework.util.StringUtils;
don't import classes from spring

2021-03-17 06:34 UTC, mrniko commented on redisson/src/main/java/org/redisson/config/SentinelServersConfig.java
> +    public SentinelServersConfig setCheckSlaveStatusWithSyncing(boolean checkSlaveStatusWithSyncing) {
add comment

2021-03-17 08:10 UTC, mikawudi commented on redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
> +import org.springframework.util.StringUtils;
can i use StringUtil from netty?

2021-03-18 10:06 UTC, mrniko approved these changes

2021-03-18 10:06 UTC, merged