Throw UOE when calling delete on an adder
redisson/redisson pull request #3482
Opened 2021-03-15 11:52 UTC by SplotyCode

Signed-off-by: david <davidscandurra@gmail.com>

2021-11-18 11:50 UTC, mrniko requested changes

2021-11-18 11:50 UTC, mrniko commented on redisson/src/main/java/org/redisson/RedissonBaseAdder.java
> +        throw new UnsupportedOperationException();
Please remove this. Since it always call `deleteAsync()` method

2021-11-19 06:04 UTC, mrniko approved these changes

2022-01-26 06:16 UTC, mrniko commented
any update?

2022-02-02 00:07 UTC, SplotyCode commented
History is a bit messed up. As I tried to sign past commits. I will fix it tomorrow

2022-10-07 08:40 UTC, mrniko commented
any update?

2022-10-13 16:08 UTC, closed without merging