fixed concurrency problems
redisson/redisson pull request #3490
Opened 2021-03-16 08:53 UTC by coding-tortoise

Signed-off-by: 小乌龟不会写代码 <41791762+coding-tortoise@users.noreply.github.com>

2021-03-16 08:55 UTC, coding-tortoise commented
set internalLockLeaseTime only when the lock acquired

2021-03-17 11:05 UTC, mrniko requested changes

2021-03-17 11:05 UTC, mrniko commented on redisson/src/main/java/org/redisson/RedissonLock.java
> +        if (-1 != leaseTime) {
rewrite it as `leaseTime = -1`

2021-03-17 11:05 UTC, mrniko commented on redisson/src/main/java/org/redisson/RedissonLock.java
> +                if (-1 != leaseTime) {
rewrite it as `leaseTime = -1`

2021-03-17 11:05 UTC, mrniko commented on redisson/src/main/java/org/redisson/RedissonLock.java
> +                if (-1 != leaseTime) {
rewrite it as `leaseTime = -1`

2021-03-18 09:50 UTC, mrniko approved these changes

2021-03-18 09:50 UTC, merged

2021-03-18 09:50 UTC, mrniko commented
Thanks for contribution!