feature: implement oldValue in jcache
redisson/redisson pull request #3531
Opened 2021-03-31 13:47 UTC by testower

Solves #3511

2021-04-02 06:05 UTC, mrniko commented
Thanks for suggested pr. According to your changes old values are sent for any listener even if old value wasn't requested. This may increase pub/sub traffic for customers who don't need it.

2021-04-02 20:48 UTC, testower commented
Thanks for the feedback, that makes sense. I'm happy to give it a shot. Let me know if you have any pointers or similar concepts already I can look at for guidance.

2021-04-07 08:59 UTC, mrniko commented
You need to introduce oldvaluelistneres counter like with name generated like in getTimeoutSetName() method. Use `incr` command in `registerCacheEntryListener` method and `decr` in `deregisterCacheEntryListener` method. Don't send old value if counter value == false.

2021-04-07 09:40 UTC, testower commented
Looks like your message crossed my draft implementation. I think we're on the same page. I have implemented for updated only, but will complete the other listeners if you think I'm on the right track here.

2021-04-09 07:43 UTC, mrniko requested changes

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +    String getUpdatedChannelOldValueRequiredCounter() { return "jcache_updated_old_value_required_counter:{" + getName() + "}"; }
can we make it shorter like `jcache_old_value_listeners` ?

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                          + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[4]), ARGV[4], string.len(ARGV[5]), ARGV[5], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                          + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[4]), ARGV[4], string.len(ARGV[5]), ARGV[5], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                    + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[i]), ARGV[i], string.len(ARGV[i+1]), ARGV[i+1], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                    + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[i]), ARGV[i], string.len(ARGV[i+1]), ARGV[i+1], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                          + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[4]), ARGV[4], string.len(ARGV[5]), ARGV[5], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                          + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[4]), ARGV[4], string.len(ARGV[5]), ARGV[5], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                      + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[4]), ARGV[4], string.len(ARGV[5]), ARGV[5], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                           + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[4]), ARGV[4], string.len(ARGV[6]), ARGV[6], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                      + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[4]), ARGV[4], string.len(ARGV[6]), ARGV[6], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                  + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[3]), ARGV[3], string.len(ARGV[4]), ARGV[4], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                  + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[3]), ARGV[3], string.len(ARGV[4]), ARGV[4], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                  + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[3]), ARGV[3], string.len(ARGV[4]), ARGV[4], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:43 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                  + "local msg = struct.pack('Lc0Lc0Lc0', string.len(ARGV[3]), ARGV[3], string.len(ARGV[4]), ARGV[4], string.len(tostring(value)), tostring(value)); "
`oldValueRequired` should be checked

2021-04-09 07:44 UTC, mrniko commented
I added few comments. Implementation looks right

2021-04-09 11:03 UTC, testower commented
I think there is a problem in the listener logic. When the first listener registers without requiring the old value it will instantiate a codec that doesn't expect it, and then another listener registers requiring the old value, then the first listener will start receiving it as well, and its codec will need to be instantiated as well. This will only result in an error when sync methods are used I think. I will try to produce a test case and look into how to solve it. Let me know if you have any suggestions.

2021-04-09 11:59 UTC, mrniko commented
I think codec needs to be modified and data with 0 length should be sent when we don't need old value.

2021-04-12 10:16 UTC, testower commented
I have updated the PR with a suggested solution. In the end, a signed short value of `-1` indicates that there is no old value in the message and the decoder can skip trying to decode it. Let me know if that's sort of what you had in mind.

2021-04-12 12:00 UTC, mrniko requested changes

2021-04-12 12:00 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                "local value = redis.call('hget', KEYS[1], ARGV[3]); "
call `hget` only if it's really needed.

2021-04-12 12:00 UTC, mrniko commented on redisson/src/main/java/org/redisson/jcache/JCache.java
> +                    "local value = redis.call('hget', KEYS[1], ARGV[3]); "
call `hget` only if it's really needed.

2021-04-14 08:38 UTC, merged

2021-04-14 08:39 UTC, mrniko commented
Thanks much for this contribution!