Create custom Trim parameter class and overload the trim methods
redisson/redisson pull request #3806
Opened 2021-09-01 12:30 UTC by ivanopagano

Fixes #3803 

Deprecate the existing XTRIM methods available in any interface where the TrimStrategy is supported, and overload with one
that accepts a generic TrimParam.

This allows to pass in different types than the current `int` values, to support the full semantics of MINID.

Such TrimParam can only be created via smart constructors, to improve on type safety and user ergonomics.

**CAVEAT**

Currently I can't manage to run the test suite, as explained in the related issue.
I'll report here the problem I have

---

I'm locally testing my fix, but I can't seem to properly run the overall tests as per instructions.

Essentially it looks like my mvn installation can't properly pick up the argLine property to feed to the tests, as the default redis binary path is not properly overridden.

This is the starting log when I try to run the mvn tests as per contribution's instructions
```
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)                                                                                                                                                                                                                  
Maven home: /usr/local/Cellar/maven/3.8.2/libexec                                                                                                                                                                                                                              
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Users/ivanopagano/.sdkman/candidates/java/11.0.11.hs-adpt                                                                                                                                                               
Default locale: en_IT, platform encoding: UTF-8                                                                                                                                                                                                                                
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
```

Are there specific jdk/mvn versions settings required to run the project, apart from what's directly configured via the pom file?

2021-09-01 15:27 UTC, mrniko commented
Thank you for proposed changes.

Did you try this example https://github.com/redisson/redisson/blob/master/.github/CONTRIBUTING.md#running-the-tests

2021-09-01 15:54 UTC, ivanopagano commented
> Thank you for proposed changes.
> 
> Did you try this example https://github.com/redisson/redisson/blob/master/.github/CONTRIBUTING.md#running-the-tests

It's exactly what fails to me in the way I showed in the description...

2021-09-02 07:06 UTC, ivanopagano commented
> I run it successfully. Windows

On this PR branch? Then I'd deem it's working...

I can't even run the `master` on my macos. First thing that fails is that mvn doesn't pick up the argLine values, hence the test environment can't properly figure out my local executable path.

Additionally, even if I override the hardcoded default to point it to my local redis-server the tests start fine, but I get multiple failures...
Could it be that the main tests are tailored to some specifics of the running env, like OS, mvn, jdk... ?

In the end, if _at least someone_ have run this branch successfully, is it considered good to go?

2021-09-02 07:28 UTC, mrniko requested changes

2021-09-02 07:30 UTC, mrniko commented on redisson/src/main/java/org/redisson/api/RStream.java
> +    long trim(TrimStrategy strategy, TrimParam param);
I have an idea how to extend API. Below is an example:

```java
trim().maxLen(10).noLimit();
trimStrict().minId(new StreamMessageId(123123));
```

2021-09-02 07:34 UTC, mrniko commented on redisson/src/main/java/org/redisson/api/RStream.java
> +    long trim(TrimStrategy strategy, TrimParam param);
Will implement that.

2021-09-02 07:39 UTC, ivanopagano commented on redisson/src/main/java/org/redisson/api/RStream.java
> +    long trim(TrimStrategy strategy, TrimParam param);
You wanna build a fluent api to have properly typed inputs?

Sounds a good idea, even tho a bit of rework. I tried to be as non-intrusive as possible. 😁

2021-09-02 08:32 UTC, mrniko commented on redisson/src/main/java/org/redisson/api/RStream.java
> +    long trim(TrimStrategy strategy, TrimParam param);
Didn't know how to make fluent api for trim. But now I know. :)

2021-09-03 06:53 UTC, mrniko commented
Fixed in https://github.com/redisson/redisson/commit/b9ed3fc743f7d8d14aa0d43e829ac90e6e12ddb3

2021-09-03 06:53 UTC, closed without merging