Added distributed iterator
redisson/redisson pull request #3970
Opened 2021-11-21 18:21 UTC by Vorotyntsev

Added distributed iterator for lists, sets, sorted sets and scored sorted sets. 
List iterator is based on `LRANGE` command, other - on `SSCAN` and `ZSCAN`

General algorithm is following:
1. Retrieve saved cursor
2. If it doesn't exist, use 0 as default
3. If cursor is -1, it's exhausted and empty result should be returned
4. Scan next `count` elements
5. Update cursor
6. For multimaps filter elements by ttl

2021-11-22 08:22 UTC, mrniko requested changes
Looks great!

But please reformat if ~ else ~ end statements according to the format used in other Lua-scripts;

```
if ... then
   ...
else 
   ...
end;
```

2021-11-22 11:38 UTC, mrniko commented on redisson/src/main/java/org/redisson/RedissonList.java
> +        List<Object> args = new ArrayList<>(1);
don't use list if arguments are static

2021-11-22 11:38 UTC, mrniko commented on redisson/src/main/java/org/redisson/RedissonListMultimapValues.java
> +        List<Object> args = new ArrayList<>(2);
don't use list if arguments are static

2021-11-22 11:39 UTC, mrniko commented on redisson/src/main/java/org/redisson/RedissonSortedSet.java
> +        List<Object> args = new ArrayList<>(1);
don't use list if arguments are static

2021-11-23 11:48 UTC, mrniko approved these changes

2021-11-24 08:19 UTC, merged

2021-11-24 08:19 UTC, mrniko commented
Thanks for contribution!

2021-11-24 09:14 UTC, Vorotyntsev commented
Glad to help. Thanks!