Check expiration before release in RedissonPermitExpirableSemaphore
redisson/redisson pull request #4091
Opened 2022-01-25 12:21 UTC by randomVariable2

Fix for issue [#4086](https://github.com/redisson/redisson/issues/4086). Checks expiry time of RedissonPermitExpirableSemaphore before releasing so that return value of releaseLock behavior is consistent  between expired and manually released locks.

2022-01-25 12:23 UTC, mrniko commented
Please cover it by test

2022-01-25 13:29 UTC, randomVariable2 commented
> Please cover it by test

Alright added test case

2022-01-26 06:15 UTC, mrniko requested changes

2022-01-26 06:15 UTC, mrniko commented on redisson/src/main/java/org/redisson/RedissonPermitExpirableSemaphore.java
> +                        "return 0;" +
shift this line to the right

2022-01-26 06:15 UTC, mrniko commented on redisson/src/main/java/org/redisson/RedissonPermitExpirableSemaphore.java
> +                        "return 0;" +
shift this line to the right

2022-01-27 05:27 UTC, mrniko commented
Please correct all checks.

2022-01-28 12:17 UTC, randomVariable2 commented
Okay, all checks passed.

2022-01-28 12:31 UTC, merged

2022-01-28 12:31 UTC, mrniko commented
Thanks for contribution