Code Review - Behaviors of FixedRate and FixedDelay should be similar in TasksRunnerService
redisson/redisson pull request #5147
Opened 2023-07-04 01:55 UTC by zcxsythenew

In `TasksRunnerService`, the behaviors of FixedRate and FixedDelay are quite different.

In method `scheduleWithFixedDelay`, we (1) execute `Runnable`, and then (2) check whether the task request id still exists, and finally (3) schedule next execution.

However, in method `scheduleAtFixedRate`, we (1) execute `Runnable`, and then (2) schedule next execution, without checking the task request id.

I believe that `FixedDelay` and `FixedRate` are similar and should not have such difference, so I raise this pull request to add a check in method `scheduleAtFixedRate`.

This pull request also addresses issue #5143 .

2023-07-04 03:57 UTC, mrniko requested changes
Thank you for suggested changes. Please add a test

2023-07-04 22:44 UTC, zcxsythenew commented
> Thank you for suggested changes. Please add a test

Done

2024-11-06 10:08 UTC, mrniko approved these changes

2024-11-06 10:15 UTC, merged

2024-11-06 10:15 UTC, mrniko commented
Thanks for contribution!