[ISSUE #5235]add aop lock annotation
redisson/redisson pull request #5240
Opened 2023-08-10 06:41 UTC by 985492783

2023-08-10 06:57 UTC, mrniko commented
Thanks for proposed changes.

2023-08-10 06:57 UTC, mrniko requested changes
Why do you mention fair lock and use spin lock? 
Can you introduce Lock type parameter? 
Test is is also required.

2023-08-10 07:11 UTC, 985492783 commented
> Why do you mention fair lock and use spin lock? Can you introduce Lock type parameter? Test is is also required.

I try to contribute to redisson first. If you think it is a good issue, i will do it more clearer and add unit test

2023-08-10 09:25 UTC, 985492783 commented
> Why do you mention fair lock and use spin lock? Can you introduce Lock type parameter? Test is is also required.

fix this error and add some unit test

2023-08-23 03:01 UTC, 985492783 commented
@mrniko review requested

2023-08-23 05:46 UTC, mrniko requested changes

2023-08-23 05:46 UTC, mrniko commented on redisson-spring-boot-starter/src/main/java/org/redisson/spring/type/LockTypeEnum.java
> +    SIMPLE,
Add comments per value

2023-08-23 05:46 UTC, mrniko commented on redisson-spring-boot-starter/src/main/java/org/redisson/spring/annotation/RMutexLock.java
> +    String name() default placeholder;
Add comments per setting

2023-09-06 09:22 UTC, 985492783 commented
@mrniko i have solved it

2023-09-13 07:35 UTC, mrniko requested changes
lock classes should be moved to redisson\src\main\java\org\redisson\spring\lock folder

2023-10-08 10:16 UTC, 985492783 commented
> lock classes should be moved to redisson\src\main\java\org\redisson\spring\lock folder

@mrniko done

2023-10-18 07:54 UTC, mrniko commented
Sorry, but it's still in org.redisson.api package

2024-02-26 11:37 UTC, closed without merging