Fix work with multiple different RLocalCachedMap in the same RTransaction
redisson/redisson pull request #5564
Opened 2024-01-14 21:47 UTC by vlad-ogol

Work with 2 different `RLocalCachedMap`s was broken. The root cause:
1. `RTransaction` tries to cache locally instances of `RedissonTransactionalLocalCachedMap`s for origin `RLocalCachedMap`s.
2. The origin `RLocalCachedMap` is used as a **key** in that local cache.
3. Keys for the local cache are calculated via`RLocalCachedMap.hashCode()` method.
4. `RLocalCachedMap.hashCode` method calculates the hash based only on map entries
5. As a result, different empty `RLocalCachedMap` were mapped to the same key and the local cache was broken.

The described case is reproduced in PR in the test `testPut2Maps`.

Proposed solution: use the name of the origin `RLocalCachedMap` as a key in the local cache.

2024-02-08 08:54 UTC, vlad-ogol commented
@mrniko please review

2024-04-26 05:14 UTC, mrniko commented
Thanks for suggested changes. I think it's better to replace new HashMap with IdentityHashMap

2024-04-26 05:15 UTC, mrniko requested changes

2024-04-26 05:15 UTC, mrniko commented on redisson/src/main/java/org/redisson/transaction/RedissonTransaction.java
> -    private final Map<RLocalCachedMap<?, ?>, RLocalCachedMap<?, ?>> localCacheInstances = new HashMap<>();
You don't need to change key type. Just replace HashMap with IdentityHashMap

2024-04-30 09:12 UTC, raja2102598 commented
@mrniko i have made the changes and commited in another PR #5829 since i dont have access to this one and i am waiting for this fix.

2024-04-30 12:18 UTC, mrniko commented
Fixed in https://github.com/redisson/redisson/pull/5829

2024-04-30 12:18 UTC, closed without merging