Fix #5426
redisson/redisson pull request #5915
Opened 2024-05-29 00:33 UTC by bclay2116

Override changeSessionId from StandardSession to copy all items in old session to new in Redis layer.
This leaves intact all logic around when Session gets written to redis (Memory vs Redis and Default vs After Update) and ensures underlying cache is exactly the same as prior to ID change.

2024-06-06 06:17 UTC, mrniko requested changes

2024-06-06 06:17 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
> +        session.tellChangedSessionId(newId, oldId, notifySessionListeners, notifyContainerListeners);
please replace it with `super.changeSessionId(session, newId, true, true);`

2024-06-06 06:17 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
> +        session.setId(newId, false);
please replace it with `super.changeSessionId(session, newId, true, true);`

2024-06-06 06:17 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
> +        session.setId(newId, false);
please replace it with super.changeSessionId(session, newId, true, true);

2024-06-06 06:17 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
> +        session.setId(newId, false);
please replace it with super.changeSessionId(session, newId, true, true);

2024-06-06 06:20 UTC, mrniko requested changes

2024-06-06 06:20 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
> +        Map<String, Object> oldMap = getMap(oldId).readAllMap();
use getMap(oldId).rename() instead

2024-06-06 06:20 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
> +        Map<String, Object> oldMap = getMap(oldId).readAllMap();
use getMap(oldId).rename() instead

2024-06-06 06:20 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
> +        Map<String, Object> oldMap = getMap(oldId).readAllMap();
use getMap(oldId).rename() instead

2024-06-06 06:20 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
> +        Map<String, Object> oldMap = getMap(oldId).readAllMap();
use getMap(oldId).rename() instead

2024-06-06 06:20 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSession.java
> -        if (map == null) {
that's not needed if map was renamed

2024-06-06 06:20 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSession.java
> -        if (map == null) {
that's not needed if the map was renamed

2024-06-06 06:20 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSession.java
> -        if (map == null) {
that's not needed if the map was renamed

2024-06-06 06:20 UTC, mrniko commented on redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java
> -        if (map == null) {
that's not needed if the map was renamed

2024-06-16 20:12 UTC, bclay2116 commented
The above comments want to use a rename approach to update map to new key (which is admittedly superior). However, invoking rename at the changeSessionId level would result in same symptoms as original issue. This is because eventually setId gets invoked within StandardSession which would inform the Manager to delete and then resave the session. In the delete, the map gets deleted. I have new approach which overrides setId to do the rename.

2024-06-17 10:42 UTC, merged

2024-06-17 10:42 UTC, mrniko commented
Thanks for contribution!