When high qps, async operation code stack may too deep
redisson/redisson pull request #5977
Opened 2024-06-22 22:36 UTC by semistone

2024-06-24 04:31 UTC, mrniko commented
Thanks for suggested changes. Can you share the example of stack you are trying to avoid?

2024-06-24 07:18 UTC, semistone commented
[stack.gz](https://github.com/user-attachments/files/15951229/stack.gz)


it's related to issue
https://github.com/redisson/redisson/issues/5971

2024-06-25 05:23 UTC, semistone commented
it's simple POC about  reduce call stack in AsyncSemaphore
```java
    private void tryRun() {
        while (true) {
            if (counter.decrementAndGet() >= 0) {
                CompletableFuture<Lock> future = listeners.poll();
                if (future == null) {
                    counter.incrementAndGet();
                    return;
                }

                if (!future.isDone()) {
                    // release only once by lock object
                    AtomicBoolean once = new AtomicBoolean();
                    AtomicBoolean tryNext = new AtomicBoolean();
                    long currentThreadId = Thread.currentThread().getId();
                    if (future.complete(() -> { <==== return release runnable 
                        if (once.compareAndSet(false, true)) {
                            // if in the same thread and tryNext is false means already release in the same thread.
                            release(Thread.currentThread().getId() != currentThreadId || tryNext.compareAndSet(false, true));
                        }
                    })) {
                        if (tryNext.compareAndSet(false, true)) { 
                            continue; // continue to tryRun  if not release yet.
                        } else {
                            return;
                        }
                    }
                }
            }

            if (counter.incrementAndGet() <= 0) {
                return;
            }
        }
    
```

I didn't test and optimism it yet.

2024-06-25 07:07 UTC, mrniko requested changes

2024-06-25 07:07 UTC, mrniko commented on redisson/src/main/java/org/redisson/connection/ConnectionsHolder.java
> +            f.thenAcceptAsync(r -> connectTo(result, command));
you need to define `serviceManager.getGroup()` as an executor.

2024-06-25 07:07 UTC, mrniko commented on redisson/src/main/java/org/redisson/connection/ConnectionsHolder.java
> +            f.thenAcceptAsync(r -> connectTo(result, command));
serviceManager.getGroup().submit(() -> {
                releaseConnection();
});

now can be replaced with only releaseConnection();

2024-06-26 04:33 UTC, semistone commented
I change to always switch thread during release as your suggestion.
I checked when that error happen, it those StackOverflowError and it's not Exception but throwable.
and the stack size is also depend on how user's implementation, it could happen after very few recursive loop. 
so switch thread in every release is  is better.

2024-06-26 04:43 UTC, semistone commented
or switch in 

```java
RedisExecutor.sendCommand
            if (connectionManager.getServiceManager().getConfig().getMasterConnectionPoolSize() < 10
                    && !command.isBlockingCommand()) {
                release(connection); <=== here
            }
```

2024-06-26 07:28 UTC, mrniko commented
Thanks for your assistance. I have fixed it in https://github.com/redisson/redisson/commit/3c1c90f60349e5f13742641819f9619a59101b08

2024-06-26 07:28 UTC, closed without merging