Performance: replace loggers for instances by loggers for classes
redisson/redisson pull request #6045
Opened 2024-07-22 19:14 UTC by Hartigan

Hi

I found some places where `redisson` creates logger for instance of class. It's slow down operations with redis(for example `getMap(String)` which creates `RedissonMap` with logger each time). I wanna propose to replace instance loggers by class loggers. 

Thank you

2024-08-08 10:55 UTC, mrniko requested changes

2024-08-08 10:55 UTC, mrniko commented on redisson-hibernate/redisson-hibernate-4/src/main/java/org/redisson/hibernate/region/BaseRegion.java
> +    private static final Logger logger = LoggerFactory.getLogger(BaseRegion.class);
this needs to remain unchanged or be added to all inheritances with concrete class, not BaseRegion.

2024-08-08 10:55 UTC, mrniko commented on redisson-hibernate/redisson-hibernate-5/src/main/java/org/redisson/hibernate/region/BaseRegion.java
> +    private static final Logger logger = LoggerFactory.getLogger(BaseRegion.class);
this needs to remain unchanged or be added to all inheritances with concrete class, not BaseRegion.

2024-08-08 10:55 UTC, mrniko commented on redisson-hibernate/redisson-hibernate-52/src/main/java/org/redisson/hibernate/region/BaseRegion.java
> +    private static final Logger logger = LoggerFactory.getLogger(BaseRegion.class);
this needs to remain unchanged or be added to all inheritances with concrete class, not BaseRegion.

2024-08-08 10:55 UTC, mrniko commented on redisson/src/main/java/org/redisson/RedissonMap.java
> +    private static final Logger log = LoggerFactory.getLogger(RedissonMap.class);
this needs to remain unchanged or be added to all inheritances with concrete class, not RedissonMap.

2024-08-08 10:55 UTC, mrniko commented on redisson/src/main/java/org/redisson/connection/pool/ConnectionPool.java
> +    private static final Logger log = LoggerFactory.getLogger(ConnectionPool.class);
this needs to remain unchanged or be added to all inheritance classes with concrete class, not ConnectionPool.

2024-08-08 10:55 UTC, mrniko commented on redisson/src/main/java/org/redisson/eviction/EvictionTask.java
> +    private static final Logger log = LoggerFactory.getLogger(EvictionTask.class);
this needs to remain unchanged or be added to all inheritance classes with concrete class, not EvictionTask.

2024-08-08 10:55 UTC, mrniko commented on redisson/src/main/java/org/redisson/remote/BaseRemoteProxy.java
> +    private static final Logger log = LoggerFactory.getLogger(BaseRemoteProxy.class);
this needs to remain unchanged or be added to all inheritance classes with concrete class, not BaseRemoteProxy.

2024-08-12 18:03 UTC, closed without merging

2024-08-12 18:03 UTC, Hartigan commented
Hello @mrniko 

To keep current behaviour, I should write caching logic for logger instances. I think better do this inside logger factory. I will close this PR.

Thanks